### PR TITLE
#234 using interlocked in Counter

### PR DESCRIPTION
**Pull request by gaufung**

### CODE REVIEW

**Comment by gaufung** [comment]
https://stackoverflow.com/questions/154551/volatile-vs-interlocked-vs-lock

**Interlocked** is faster

**Review by Anduin2017 — APPROVED** [review]

**Comment by Anduin2017** [comment]
Awesome fix!!! Thank you for the contribution!

However, the ci rejected. It seems might not be your issue. Before I can merge this, that would be really nice if you can help fix the build. Thank you!

**Comment by Anduin2017** [comment]
By the way, the first value from the counter must not be zero. Because some validator is treating 0 as an invalid input. Giving 0 might cause our business misbehaving.

**Review by Anduin2017 — CHANGES_REQUESTED** [review]
By the way, the first value from the counter must not be zero. Because some validator is treating 0 as an invalid input. Giving 0 might cause our business misbehaving.

**Review by Anduin2017 — APPROVED** [review]

**Pull request merged**
